export const deliveryCharge = 5.9

export const COFFES_LIST = [
  {
    img: './src/assets/expresso.png',
    price: 9.99,
    tags: ['TRADICIONAL'],
    name: 'Expresso Tradicional',
    desc: 'O tradicional café feito com água quente e grãos moídos',
  },
  {
    img: './src/assets/americano.png',
    price: 9.99,
    tags: ['TRADICIONAL'],
    name: 'Expresso Americano',
    desc: 'Expresso diluído, menos intenso que o tradicional',
  },
  {
    img: './src/assets/expresso-cremoso.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'GELADO'],
    name: 'Expresso Cremoso',
    desc: 'Café expresso tradicional com espuma cremosa',
  },
  {
    img: './src/assets/cafe-gelado.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'GELADO'],
    name: 'Expresso Gelado',
    desc: 'Bebida preparada com café expresso e cubos de gelo',
  },

  {
    img: './src/assets/cafe-com-leite.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Café com Leite',
    desc: 'Meio a meio de expresso tradicional com leite vaporizado',
  },
  {
    img: './src/assets/latte.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Latte',
    desc: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
  },
  {
    img: './src/assets/capuccino.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Capuccino',
    desc: 'Bebida com canela feita de doses iguais de café, leite e espuma',
  },
  {
    img: './src/assets/macchiato.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Machiatto',
    desc: 'Café expresso misturado com um pouco de leite quente e espuma',
  },
  {
    img: './src/assets/mocaccino.png',
    price: 9.99,
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Mocaccino',
    desc: 'Café expresso com calda de chocolate, pouco leite e espuma',
  },
  {
    img: './src/assets/chocolate-quente.png',
    price: 9.99,
    tags: ['ESPECIAL', 'COM LEITE'],
    name: 'Chocolate Quente',
    desc: 'Bebida feita com chocolate dissolvido no leite quente e café',
  },
  {
    img: './src/assets/cubano.png',
    price: 9.99,
    tags: [''],
    name: 'Cubano',
    desc: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
  },
  {
    img: './src/assets/havaiano.png',
    price: 9.99,
    tags: [''],
    name: 'Havaiano',
    desc: 'Bebida adocicada preparada com café e leite de coco',
  },
  {
    img: './src/assets/arabe.png',
    price: 9.99,
    tags: ['ESPECIAL'],
    name: 'Árabe',
    desc: 'Bebida preparada com grãos de café árabe e especiarias',
  },
  {
    img: './src/assets/irlandes.png',
    price: 9.99,
    tags: [''],
    name: 'Irlândes',
    desc: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
  },
]
